# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('number_of_page', models.IntegerField(blank=True, null=True)),
                ('type_of_book', models.CharField(blank=True, choices=[('novel', 'Novel'), ('documentation', 'Documentation'), ('other', 'Other')], max_length=300, null=True)),
            ],
        ),
    ]
